apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mainstay
  name: mainstay
  namespace: ${Environment}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mainstay
  template:
    metadata:
      labels:
        app: mainstay
    spec:
      containers:
        - image: 'cremerfc/flask-app:${buildTag}'
          name: flask-app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mainstay-service
  namespace: ${Environment}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: mainstay
  type: LoadBalancer
